FROM python:3.13.7-slim

WORKDIR /app

RUN mkdir unified_review_data

COPY requirements.txt .

RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

COPY review_scraper.py .

CMD ["python", "review_scraper.py"]